In [1]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\vijay\appdata\local\python\pythoncore-3.14-64\lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\vijay\appdata\local\python\pythoncore-3.14-64\lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in c:\users\vijay\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from sqlalchemy) (3.5.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\vijay\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pymysql
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine

In [27]:
df = pd.read_csv("E:/downloads/ICRISAT-District Level Data - ICRISAT-District Level Data.csv")

df.head()

,Dist Code,Year,State Code,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
0,1,1966,14,Chhattisgarh,Durg,548.0,185.0,337.59,44.0,20.0,...,1777.78,0.0,0.0,0.0,5.95,6.64,12.59,0.01,0.60,0.47
1,1,1967,14,Chhattisgarh,Durg,547.0,409.0,747.71,50.0,26.0,...,1500.00,0.0,0.0,0.0,5.77,7.24,13.02,0.01,0.56,1.23
2,1,1968,14,Chhattisgarh,Durg,556.3,468.0,841.27,53.7,30.0,...,1000.00,0.0,0.0,0.0,5.41,7.40,12.81,0.10,0.58,1.02
3,1,1969,14,Chhattisgarh,Durg,563.4,400.8,711.40,49.4,26.5,...,1900.00,0.0,0.0,0.0,5.52,7.16,12.69,0.01,0.56,0.84
4,1,1970,14,Chhattisgarh,Durg,571.6,473.6,828.55,44.2,29.0,...,2000.00,0.0,0.0,0.0,5.45,7.19,12.64,0.02,0.52,0.42

In [28]:
df.columns = df.columns.str.replace(' ', '_').str.lower()
df.columns =df.columns.str.removesuffix('_(1000_tons)')
df.columns =df.columns.str.removesuffix('_(1000_ha)')
df.columns =df.columns.str.removesuffix('_(kg_per_ha)')

In [5]:
# yeild = kg per ha
#production = 1000 tons
#area = 1000 ha

In [29]:
df.head()

,dist_code,year,state_code,state_name,dist_name,rice_area,rice_production,rice_yield,wheat_area,wheat_production,...,sugarcane_yield,cotton_area,cotton_production,cotton_yield,fruits_area,vegetables_area,fruits_and_vegetables_area,potatoes_area,onion_area,fodder_area
0,1,1966,14,Chhattisgarh,Durg,548.0,185.0,337.59,44.0,20.0,...,1777.78,0.0,0.0,0.0,5.95,6.64,12.59,0.01,0.60,0.47
1,1,1967,14,Chhattisgarh,Durg,547.0,409.0,747.71,50.0,26.0,...,1500.00,0.0,0.0,0.0,5.77,7.24,13.02,0.01,0.56,1.23
2,1,1968,14,Chhattisgarh,Durg,556.3,468.0,841.27,53.7,30.0,...,1000.00,0.0,0.0,0.0,5.41,7.40,12.81,0.10,0.58,1.02
3,1,1969,14,Chhattisgarh,Durg,563.4,400.8,711.40,49.4,26.5,...,1900.00,0.0,0.0,0.0,5.52,7.16,12.69,0.01,0.56,0.84
4,1,1970,14,Chhattisgarh,Durg,571.6,473.6,828.55,44.2,29.0,...,2000.00,0.0,0.0,0.0,5.45,7.19,12.64,0.02,0.52,0.42

In [30]:
df.columns

Index(['dist_code', 'year', 'state_code', 'state_name', 'dist_name',
       'rice_area', 'rice_production', 'rice_yield', 'wheat_area',
       'wheat_production', 'wheat_yield', 'kharif_sorghum_area',
       'kharif_sorghum_production', 'kharif_sorghum_yield',
       'rabi_sorghum_area', 'rabi_sorghum_production', 'rabi_sorghum_yield',
       'sorghum_area', 'sorghum_production', 'sorghum_yield',
       'pearl_millet_area', 'pearl_millet_production', 'pearl_millet_yield',
       'maize_area', 'maize_production', 'maize_yield', 'finger_millet_area',
       'finger_millet_production', 'finger_millet_yield', 'barley_area',
       'barley_production', 'barley_yield', 'chickpea_area',
       'chickpea_production', 'chickpea_yield', 'pigeonpea_area',
       'pigeonpea_production', 'pigeonpea_yield', 'minor_pulses_area',
       'minor_pulses_production', 'minor_pulses_yield', 'groundnut_area',
       'groundnut_production', 'groundnut_yield', 'sesamum_area',
       'sesamum_production', 'sesamum_yield', 'rapeseed_and_mustard_area',
       'rapeseed_and_mustard_production', 'rapeseed_and_mustard_yield',
       'safflower_area', 'safflower_production', 'safflower_yield',
       'castor_area', 'castor_production', 'castor_yield', 'linseed_area',
       'linseed_production', 'linseed_yield', 'sunflower_area',
       'sunflower_production', 'sunflower_yield', 'soyabean_area',
       'soyabean_production', 'soyabean_yield', 'oilseeds_area',
       'oilseeds_production', 'oilseeds_yield', 'sugarcane_area',
       'sugarcane_production', 'sugarcane_yield', 'cotton_area',
       'cotton_production', 'cotton_yield', 'fruits_area', 'vegetables_area',
       'fruits_and_vegetables_area', 'potatoes_area', 'onion_area',
       'fodder_area'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16146 entries, 0 to 16145
Data columns (total 80 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   dist_code                        16146 non-null  int64
 1   year                             16146 non-null  int64
 2   state_code                       16146 non-null  int64
 3   state_name                       16146 non-null  object
 4   dist_name                        16146 non-null  object
 5   rice_area                        16146 non-null  float64
 6   rice_production                  16146 non-null  float64
 7   rice_yield                       16146 non-null  float64
 8   wheat_area                       16146 non-null  float64
 9   wheat_production                 16146 non-null  float64
 10  wheat_yield                      16146 non-null  float64
 11  kharif_sorghum_area              16146 non-null  float64
 12  kharif_sorghum_production        16146 non-null  float64
 13  kharif_sorghum_yield             16146 non-null  float64
 14  rabi_sorghum_area                16146 non-null  float64
 15  rabi_sorghum_production          16146 non-null  float64
 16  rabi_sorghum_yield               16146 non-null  float64
 17  sorghum_area                     16146 non-null  float64
 18  sorghum_production               16146 non-null  float64
 19  sorghum_yield                    16146 non-null  float64
 20  pearl_millet_area                16146 non-null  float64
 21  pearl_millet_production          16146 non-null  float64
 22  pearl_millet_yield               16146 non-null  float64
 23  maize_area                       16146 non-null  float64
 24  maize_production                 16146 non-null  float64
 25  maize_yield                      16146 non-null  float64
 26  finger_millet_area               16146 non-null  float64
 27  finger_millet_production         16146 non-null  float64
 28  finger_millet_yield              16146 non-null  float64
 29  barley_area                      16146 non-null  float64
 30  barley_production                16146 non-null  float64
 31  barley_yield                     16146 non-null  float64
 32  chickpea_area                    16146 non-null  float64
 33  chickpea_production              16146 non-null  float64
 34  chickpea_yield                   16146 non-null  float64
 35  pigeonpea_area                   16146 non-null  float64
 36  pigeonpea_production             16146 non-null  float64
 37  pigeonpea_yield                  16146 non-null  float64
 38  minor_pulses_area                16146 non-null  float64
 39  minor_pulses_production          16146 non-null  float64
 40  minor_pulses_yield               16146 non-null  float64
 41  groundnut_area                   16146 non-null  float64
 42  groundnut_production             16146 non-null  float64
 43  groundnut_yield                  16146 non-null  float64
 44  sesamum_area                     16146 non-null  float64
 45  sesamum_production               16146 non-null  float64
 46  sesamum_yield                    16146 non-null  float64
 47  rapeseed_and_mustard_area        16146 non-null  float64
 48  rapeseed_and_mustard_production  16146 non-null  float64
 49  rapeseed_and_mustard_yield       16146 non-null  float64
 50  safflower_area                   16146 non-null  float64
 51  safflower_production             16146 non-null  float64
 52  safflower_yield                  16146 non-null  float64
 53  castor_area                      16146 non-null  float64
 54  castor_production                16146 non-null  float64
 55  castor_yield                     16146 non-null  float64
 56  linseed_area                     16146 non-null  float64
 57  linseed_production               16146 non-null  float64
 58  linseed_yield                    16146 non-null  float64
 59  sunflower_area                   16146 non-null  float64
 60  sunflower_production             16146 non-null  float64
 61  sunflower_yield                  16146 non-null  float64
 62  soyabean_area                    16146 non-null  float64
 63  soyabean_production              16146 non-null  float64
 64  soyabean_yield                   16146 non-null  float64
 65  oilseeds_area                    16146 non-null  float64
 66  oilseeds_production              16146 non-null  float64
 67  oilseeds_yield                   16146 non-null  float64
 68  sugarcane_area                   16146 non-null  float64
 69  sugarcane_production             16146 non-null  float64
 70  sugarcane_yield                  16146 non-null  float64
 71  cotton_area                      16146 non-null  float64
 72  cotton_production                16146 non-null  float64
 73  cotton_yield                     16146 non-null  float64
 74  fruits_area                      16146 non-null  float64
 75  vegetables_area                  16146 non-null  float64
 76  fruits_and_vegetables_area       16146 non-null  float64
 77  potatoes_area                    16146 non-null  float64
 78  onion_area                       16146 non-null  float64
 79  fodder_area                      16146 non-null  float64
dtypes: float64(75), int64(3), object(2)
memory usage: 9.9+ MB

In [15]:
df.isnull().sum()

dist_code                     0
year                          0
state_code                    0
state_name                    0
dist_name                     0
                             ..
vegetables_area               0
fruits_and_vegetables_area    0
potatoes_area                 0
onion_area                    0
fodder_area                   0
Length: 80, dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [18]:
engine = create_engine('mysql+pymysql://root:1015@localhost:3306/Agriculture')

In [20]:
df.to_sql('agri_data', con=engine, if_exists='replace', index=False)

16146

In [21]:
sql_connection = pymysql.connect(host='localhost', user='root', password='1015', database='Agriculture')
cur = sql_connection.cursor()

In [22]:
Year_wise_Trend_of_Rice_Production_Across_States  = cur.execute("select state_name,year,sum(rice_production) as rice_production from agri_data GROUP BY year, state_name ORDER BY year, state_name desc limit 3;")

In [32]:
Top_5_Districts_by_Wheat_Yield_Increase_Over_the_Last_5_Years = cur.execute("SELECT dist_name, year,(wheat_yield - LAG(wheat_yield) OVER (PARTITION BY dist_name ORDER BY year)) AS yield_increase FROM agri_data ORDER BY year DESC LIMIT 5;")

In [34]:
#States with the Highest Growth in Oilseed Production (5-Year Growth Rate)
Oilseed_Production_Growth = cur.execute("SELECT state_name, ((MAX(oilseeds_production) - MIN(oilseeds_production)) / MIN(oilseeds_production)) * 100 AS growth_rate FROM agri_data GROUP BY state_name ORDER BY growth_rate DESC LIMIT 5;")

In [49]:
# Yearly Production Growth of Cotton in Top 5 Cotton Producing States

cotton_production_growth = cur.execute("select state_name, (sum(cotton_production) - lag(sum(cotton_production)) over (partition by state_name order by year)) as yearly_growth from agri_data group by state_name, year order by yearly_growth desc limit 5;")

In [ ]:
# Districts with the Highest Groundnut Production in 2017
highest_groundnut_2017 = cur.execute("SELECT dist_name, groundnut_production FROM agri_data WHERE year = 2017 ORDER BY groundnut_production DESC LIMIT 5;")

In [42]:
# Annual Average Maize Yield Across All States
annual_avg_maize_yield = cur.execute("SELECT state_name, AVG(maize_yield) AS avg_yield FROM agri_data GROUP BY state_name;")

In [44]:
# Total Area Cultivated for Oilseeds in Each State
total_oilseed_area = cur.execute("SELECT state_name, SUM(oilseeds_area) AS total_area FROM agri_data GROUP BY state_name;")

In [46]:
# Districts with the Highest Rice Yield
highest_rice_yield = cur.execute("SELECT dist_name, rice_yield FROM agri_data ORDER BY rice_yield DESC LIMIT 5;")

In [48]:
# Compare the Production of Wheat and Rice for the Top 5 States Over 10 Years
top_5_states = cur.execute("""SELECT
    year,
    state_name,
    SUM(rice_production) AS total_rice_production,
    SUM(wheat_production) AS total_wheat_production
FROM agri_data
WHERE year >= (SELECT MAX(year) - 9 FROM agri_data)
GROUP BY year, state_name
ORDER BY state_name, year;""")